### ISSUE TITLE
Meetup Day-Of Checklist

### ISSUE THREAD

**Issue by ecgeiser** [reactdc/organizers#6]
- [ ] email Angelina RSVP list by 12:00 pm
- [ ] let Angelina know desired setup by 5:30 pm
- [ ] order food to arrive by 6:50 pm
- [ ] get beverages (including non-alcoholic) by 6:50 pm
- [ ] greeter(s) should be in lobby from 6:40-7:20 pm
